# Generated by Django 4.1.1 on 2023-01-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
